name: Deploy Frontend to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest

    steps:
      # ✅ Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # ✅ Set up Node.js for Frontend Build
      - name: Setup Node.js
        uses: actions/setup-node@v20
        with:
          node-version: 20
          cache: "npm"
          cache-dependency-path: frontend/package-lock.json

      # ✅ Install Dependencies
      - name: Install Dependencies
        working-directory: frontend
        run: npm install

      # ✅ Build React App
      - name: Build Frontend
        working-directory: frontend
        run: npm run build

      # ✅ Setup SSH Key for EC2
      - name: Setup SSH Key
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" | tr -d '\r' > private_key.pem
          chmod 600 private_key.pem

      # ✅ Deploy to AWS EC2
      - name: Deploy Frontend to AWS EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key.pem ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
            # 🔹 Navigate to frontend directory
            cd /home/ubuntu/app/frontend || { mkdir -p /home/ubuntu/app/frontend && cd /home/ubuntu/app/frontend; }

            # 🔹 Pull latest code
            sudo git pull origin main

            # 🔹 Build & Run Docker container for frontend
            sudo docker stop frontend-container || true
            sudo docker rm frontend-container || true
            sudo docker rmi frontend-image || true
            
            sudo docker build -t frontend-image .
            sudo docker run -d --name frontend-container -p 3000:3000 frontend-image
          EOF
