name: Deploy Frontend to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest

    steps:
      # ✅ Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to AWS ECR
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${{ secrets.AWS_ECR_URI }}

      - name: Build and Push Frontend Docker Image
        run: |
          docker build -t todo-frontend .
          docker tag todo-frontend ${{ secrets.AWS_ECR_URI }}/todo-frontend:latest
          docker push ${{ secrets.AWS_ECR_URI }}/todo-frontend:latest

      # ✅ Deploy to AWS EC2
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: |
            ${{ secrets.EC2_SSH_KEY }}

          script: |
            aws ecr get-login-password --region us-east-1 | sudo docker login --username AWS --password-stdin ${{ secrets.AWS_ECR_URI }}
            sudo docker stop todo-frontend || true
            sudo docker rm todo-frontend || true
            sudo docker pull ${{ secrets.AWS_ECR_URI }}/todo-frontend:latest
            sudo docker run -d -p 5173:5173 --name todo-frontend ${{ secrets.AWS_ECR_URI }}/todo-frontend:latest
